version: 2
jobs:
  build:
    working_directory: ~/CNChat
    docker:
      - image: circleci/openjdk:8-stretch-node
      - image: circleci/mariadb:stretch
    steps:
      - checkout
      - run:
          name: Build1
          command: echo 1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
